### ISSUE TITLE
要不要考虑把 repo 迁移到 ChessTerm 下面

### ISSUE THREAD

**Issue by JingBh** [zhc7/flamechess-package#2]

**Comment by zhc7** [comment]
@JingBh 是不是比较麻烦

**Comment by JingBh** [comment]
@zhc7 在设置里一键修改 不麻烦的

**Comment by JingBh** [comment]
怎么样？

**Comment by JingBh** [comment]
![...?](https://user-images.githubusercontent.com/26338708/89324830-79909100-d6ba-11ea-8658-856bb06c54e8.gif)

**Comment by zhc7** [comment]
@JingBh 这样会不会导致repo所有权变化。。
